name = "hal"
description = ""
version = "0.1.0-dev"

authors = ["lgeh"]
maintainers = ["lgehu <lauric_gehu@etu.u-bourgogne.fr>"]
maintainers-logins = ["lgehu"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["hal", "adl"]



[origin]
hashes = [
"sha256:52ff3cf78650c20e0ea3f8a5eb9b388d78cb2bc9ff7cc1cc910e67c5464cf992",
"sha512:4ab8f969c03f33f0ddb87d1ed3f6f6ecf0e7426bb69591a6d456517c5b898ad8b16819cec2656744abcb433f3d5ff6054a8950740ca145848a5762b00d52d52e",
]
url = "https://github.com/lgehu/alr_adl_crates/raw/refs/heads/remote-dep/hal/hal-0.1.0-dev.tgz"

